on:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - main

name: Source Code Health

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run rss:build

    - name: RSS Build
      run: npm run rss:build

    - name: RSS Check Format
      run: npm run rss:format-check

    - name: RSS Validate
      run: npm run rss:validate
